#!/bin/sh
# chkconfig: 123456 90 10
# webapp
#
workdir="/bakkle/www/bakkle/"
apppath=$workdir"manage.py"
configfile="runserver 0.0.0.0:8000"
#configfile=$workdir"dev.conf"

start() {
    cd $workdir
    /usr/bin/python $apppath $configfile > /bakkle/log/bakkle.log &
    echo "Server started."
}

stop() {
    pid=`ps -ef | grep "[p]ython "$apppath | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/$0 {start|stop|restart}"
    exit 1
esac
exit 0

