#!/bin/bash
# chkconfig: 123456 90 10
# webapp
#
workdir="/bakkle/www/bakkle/"
apppath=$workdir"bakkleServer.py"
#configfile=$workdir"dev.conf"

DATABASE=default
if [ `hostname` == 'ip-172-31-21-18' ]; then
   DATABASE=production
fi
if [ `hostname` == 'ip-172-31-27-192' ]; then
   DATABASE=production
fi
if [ `hostname` == 'bakkle' ]; then
   DATABASE=testdb
fi
if [ `hostname` == 'rhv-bakkle-bld' ]; then
   DATABASE=dev
fi
if [ `hostname` == 'RHV-291SCS-Linux' ]; then
   DATABASE=dev
fi

start() {
    cd $workdir
    DJANGO_DATABASE=$DATABASE /usr/bin/python $apppath > /bakkle/log/bakkle.log &
    echo "Server started using DB=$DATABASE."
}

stop() {
    pid=`ps -ef | grep "[p]ython "$apppath | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "Server killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/$0 {start|stop|restart}"
    exit 1
esac
exit 0

