platform :ios, '8.0'
use_frameworks!
target 'Bakkle' do
  pod 'HanekeSwift'
  #, '~> 0.9.1'
  pod 'FontAwesomeIconFactory'
  pod 'SocketRocket'
  #, '~> 0.4.1'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit', '~> 4.5.1'
  pod 'FBSDKShareKit'
  pod 'Reachability'
  pod 'Bolts'
  #, '~> 1.5.0'
end
