platform :ios, '8.0'
use_frameworks!
target 'Bakkle' do
  pod 'Bolts', '~> 1.5.0'
  pod 'HanekeSwift', '~> 0.9.1'
  pod 'FontAwesomeIconFactory'
  pod 'SocketRocket', '~> 0.4.1'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Reachability'
  pod 'TCMobileProvision'
end
